version: '3.5'

# приближенный к продакшену конфиг
services:
          application-backend:
            build: .
            #image: php:7.4.23-fpm-alpine3.13
            tty: true
            working_dir: /var/www/application/public
            volumes:
                  - .:/var/www/application/public/
            container_name: application-backend

# Nginx Service
          application-nginx:
            image: nginx:alpine
            container_name: application-nginx
            tty: true
            environment:
              - "APPLICATION_UPSTREAM=application-backend:9000"
            volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./public/:/var/www/application/public/public/
            ports:
                - "80:80"
  # MySQL
          database:
            image: library/mysql:8.0
            container_name: "database"
            ports:
              - "3306:3306"
            volumes:
              - ./data:/docker-entrypoint-initdb.d
              - ./data:/var/lib/mysql
              - ./data:/var/log/mysql
            environment:
              MYSQL_ROOT_PASSWORD: 111
              MYSQL_DATABASE: app
              MYSQL_USER: user
              MYSQL_PASSWORD: 111
          phpmyadmin:
            image: phpmyadmin
            container_name: "phpmyadmin"
            links:
              - database
            environment:
              PMA_HOST: database
              PMA_PORT: 3306
              MYSQL_ROOT_PASSWORD: 111
            ports:
              - "8080:80"
